spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: USER-ROLE-SERVICE
          uri: lb://USER-ROLE-SERVICE
          predicates:
            - Path=/auth/**
        - id: USER-ROLE-SERVICE
          uri: lb://USER-ROLE-SERVICE
          predicates:
            - Path=/role/**
        - id: USER-ROLE-SERVICE
          uri: lb://USER-ROLE-SERVICE
          predicates:
            - Path=/user/**
        - id: JOB-CANDIDATE-COMPANY-SERVICE
          uri: lb://JOB-CANDIDATE-COMPANY-SERVICE
          predicates:
            - Path=/career/**
          filters:
#            - RewritePath=/candidate/(?<segment>.*),/api/$\{segment}
            - name: CircuitBreaker
              args:
                name: careerCenterError
                fallbackUri: forward:/errorbreaker
            - name: CircuitBreaker
              args:
                name: careerCenterResponseTime
                fallbackUri: forward:/timebreaker
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
management:
  endpoints:
    web:
      exposure:
        include=gateway:
jwt:
  secret: secretkey

eureka:
  client:
    eureka-server-connect-timeout-seconds: 5
    enabled: true
    fetch-registry: false
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka-1-server.com:8761/eureka

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

server:
  port: 8765


resilience4j:
  circuitbreaker:
    instances:
      careerCenterError:
        slidingWindowSize: 5                     #unit request
        permittedNumberOfCallsInHalfOpenState: 5  #unit request
        failureRateThreshold: 50                  #percent
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 20000
        waitDurationInOpenState: 10000            #10 seconds
        registerHealthIndicator: true
  timelimiter:
    instances:
      careerCenterResponseTime:
        timeoutDuration: 2s