server:
  port: 9191
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: STUDENTS-SERVICE
          uri: lb://STUDENTS-SERVICE
          predicates:
            - Path=/student/api/**
          filters:
            - name: CircuitBreaker
              args:
                name: studentCircuitBreaker
                fallbackUri: forward:/fallback/studentFallBack
        - id: GRADES-SERVICE
          uri: lb://GRADES-SERVICE
          predicates:
            - Path=/grade/api/**
          filters:
            - name: CircuitBreaker
              args:
                name: gradeCircuitBreaker
                fallbackUri: forward:/fallback/gradeFallBack



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
