server:
  port: 9002
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=tempdb;encrypt=true;trustServerCertificate=true
    username: sa
    password: sa
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
      show-sql: true
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
  application:
    name: GRADES-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
