spring:
  profiles: default
  application:
  name: eureka-server-clustered
server:
  port: 8761
eureka:
  instance:
    hostname: eureka-1-server.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    defaultZone: http://eureka-2-server.com:8762/eureka/,http://eureka-3-server.com:8763/eureka/
#---
#spring:
#  profiles: eureka2
#  application:
#    name: eureka-server-clustered
#server:
#  port: 8762
#eureka:
#  instance:
#    hostname: eureka-2-server.com
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    defaultZone: http://eureka-3-server.com:8763/eureka/,http://eureka-1-server.com:8761/eureka/
#---
#spring:
#  profiles: eureka3
#  application:
#  name: eureka-server-clustered
#server:
#  port: 8763
#eureka:
#  instance:
#    hostname: eureka-3-server.com
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    defaultZone: http://eureka-2-server.com:8762/eureka/,http://eureka-1-server.com:8761/eureka/
