pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..##################'
                cd genspark-training/CareerCenter/job-candidate-company-service
                c:/apache-maven-3.8.6/bin/mvn clean install -DskipTests

            }
        }
        stage('Test') {
            steps {
                echo 'Testing.. #####################'
                c:/apache-maven-3.8.6/bin/mvn test
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
