pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..##################'
                bat """CareerCenter\\job-candidate-company-service\\mvninstall.bat """
                    }
        }
        stage('Test') {
            steps {
                echo 'Testing.. #####################'
                bat """CareerCenter\\job-candidate-company-service\\mvntest.bat """
                    }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
