pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..##################'
                bat """ cd CareerCenter\\job-candidate-company-service"""
                bat """mvninstall.bat """
                    }
        }
        stage('Test') {
            steps {
                echo 'Testing.. #####################'
                mvn test
                    }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
